version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: monthly
  allow:
    - dependency-type: "production"
  open-pull-requests-limit: 10
  reviewers:
    - kyushun
  assignees:
    - kyushun
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
    - kyushun
  assignees:
    - kyushun
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
